# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('o', 'open'), ('c', 'closed'), ('a', 'assigned')], max_length=8)),
                ('resolved', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.Staff')),
            ],
        ),
    ]
