# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='staff',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.Staff'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('o', 'open'), ('c', 'closed'), ('a', 'assigned')], default='o', max_length=8),
        ),
    ]
